=== dristi2365/web-tech-lab-works/Lab4/q3.xsd
<?xml version="1.0" encoding="UTF-8"?>
<xs:schema xmlns:xs="http://www.w3.org/2001/XMLSchema">
    <xs:element name="books">
        <xs:complexType><xs:sequence>
            <xs:element name="book" maxOccurs="unbounded">
                <xs:complexType>
                    <xs:sequence>
                        <xs:element name="name">
                            <xs:complexType><xs:sequence>
                                <xs:element name="firstname" type="xs:string"/>
                                <xs:element name="middlename" type="xs:string"/>
                                <xs:element name="lastname" type="xs:string"/>
                            </xs:sequence></xs:complexType>
                        </xs:element>
                        <xs:element name="author" type="xs:string" maxOccurs="unbounded"/>
                        <xs:element name="pageno" type="xs:integer"/>
                        <xs:element name="price">
                            <xs:simpleType><xs:restriction base="xs:integer">
                                <xs:maxInclusive value="1000"/>
                            </xs:restriction></xs:simpleType>
                        </xs:element>
                    </xs:sequence>
                    <xs:attribute name="isbn" type="xs:string" use="required"/>
                </xs:complexType>
            </xs:element>
        </xs:sequence></xs:complexType>
    </xs:element>
</xs:schema>

=== dristi2365/web-tech-lab-works/Lab4/q3.xml
<?xml version="1.0" encoding="UTF-8"?>
<!-- Q3: Valid XML to validate book details -->
<books xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xsi:noNamespaceSchemaLocation="q3.xsd">
    <book isbn="978-0262033848">
        <name><firstname>Introduction</firstname><middlename>to</middlename><lastname>Algorithms</lastname></name>
        <author>Thomas Cormen</author><author>Charles Leiserson</author>
        <pageno>1292</pageno><price>850</price>
    </book>
</books>
